// AUTO-GENERATED by scripts/ingest/lsa-generate-stubs.ts. Do not edit by hand.
import type { Major } from '@/lib/types';
import p1 from './lsa-afroamerican-and-african-studies.json';
import p2 from './lsa-american-culture.json';
import p3 from './lsa-anthropology.json';
import p4 from './lsa-archaeology-of-the-ancient-mediterranean.json';
import p5 from './lsa-arts-and-ideas-in-the-humanities.json';
import p6 from './lsa-asian-studies.json';
import p7 from './lsa-astronomy-and-astrophysics.json';
import p8 from './lsa-biochemistry-bs.json';
import p9 from './lsa-biology.json';
import p10 from './lsa-biomolecular-science-ab-or-bs.json';
import p11 from './lsa-biophyschology-cognition-and-neuroscience-bcn.json';
import p12 from './lsa-biophysics-bs.json';
import p13 from './lsa-biotechnology-and-bioenvironmental-sciences.json';
import p14 from './lsa-cell-and-molecular-biology-and-biomedical-engineering.json';
import p15 from './lsa-cell-and-molecular-biology.json';
import p16 from './lsa-chemistry.json';
import p17 from './lsa-classical-civilization.json';
import p18 from './lsa-classical-languages-and-literatures.json';
import p19 from './lsa-cognitive-science.json';
import p20 from './lsa-communication-studies.json';
import p21 from './lsa-comparative-literature-arts-and-media.json';
import p23 from './lsa-creative-writing-and-literature.json';
import p24 from './lsa-data-science.json';
import p25 from './lsa-drama.json';
import p26 from './lsa-earth-and-environmental-sciences.json';
import p27 from './lsa-ecology-and-evolutionary-biology-eeb.json';
import p28 from './lsa-economics.json';
import p29 from './lsa-english.json';
import p30 from './lsa-environment.json';
import p31 from './lsa-french-and-francophone-studies.json';
import p32 from './lsa-gender-and-health.json';
import p33 from './lsa-general-biology.json';
import p34 from './lsa-general-studies.json';
import p35 from './lsa-german.json';
import p36 from './lsa-greek-ancient-language-and-literature.json';
import p37 from './lsa-greek-modern-language-and-culture.json';
import p38 from './lsa-history-of-art.json';
import p39 from './lsa-history.json';
import p40 from './lsa-human-origins-biology-and-behavior.json';
import p41 from './lsa-interdisciplinary-astronomy-ba-or-bs.json';
import p42 from './lsa-interdisciplinary-chemical-sciences-ics-ab-or-bs.json';
import p43 from './lsa-interdiscplinary-physics-ab-or-bs.json';
import p44 from './lsa-international-studies.json';
import p45 from './lsa-italian.json';
import p46 from './lsa-judaic-studies.json';
import p47 from './lsa-latin-american-and-caribbean-studies.json';
import p48 from './lsa-latin-language-and-literature.json';
import p49 from './lsa-latina-latino-studies.json';
import p50 from './lsa-linguistics.json';
import p51 from './lsa-mathematics.json';
import p52 from './lsa-microbiology.json';
import p53 from './lsa-middle-eastern-and-north-african-studies.json';
import p54 from './lsa-near-eastern-studies.json';
import p55 from './lsa-neuroscience.json';
import p56 from './lsa-organizational-studies.json';
import p57 from './lsa-philosophy-political-science-economics.json';
import p58 from './lsa-philosophy.json';
import p59 from './lsa-physics.json';
import p60 from './lsa-polish.json';
import p61 from './lsa-political-science.json';
import p62 from './lsa-psychology-general-social-science.json';
import p63 from './lsa-romance-languages-and-literatures.json';
import p64 from './lsa-russian-east-european-and-eurasian-studies.json';
import p65 from './lsa-russian.json';
import p66 from './lsa-screen-arts-and-cultures.json';
import p67 from './lsa-social-theory-and-practice.json';
import p68 from './lsa-sociology.json';
import p69 from './lsa-spanish.json';
import p70 from './lsa-statistics.json';
import p71 from './lsa-translation.json';
import p72 from './lsa-womens-studies.json';
import p73 from './lsa-computer-science-2.json';
import c1 from './coe-aerospace-engineering.json';
import c2 from './coe-biomedical-engineering.json';
import c3 from './coe-chemical-engineering.json';
import c4 from './coe-civil-engineering.json';
import c5 from './coe-climate-and-meteorology.json';
import c6 from './coe-computer-engineering.json';
import c7 from './coe-computer-science.json';
import c8 from './coe-data-science.json';
import c9 from './coe-electrical-engineering.json';
import c10 from './coe-engineering-physics.json';
import c11 from './coe-environmental-engineering.json';
import c12 from './coe-industrial-and-operations-engineering.json';
import c13 from './coe-materials-science-and-engineering.json';
import c14 from './coe-mechanical-engineering.json';
import c15 from './coe-naval-architecture-and-marine-engineering.json';
import c16 from './coe-nuclear-engineering-and-radiological-sciences.json';
import c17 from './coe-robotics.json';
import c18 from './coe-space-sciences-and-engineering.json';
import r1 from './ross-business-administration.json';
import u1 from './umsi-information-analysis.json';
import u2 from './umsi-ux-design.json';
import s1 from './smtd-ba-music.json';
import s2 from './smtd-bfa-acting.json';
import s3 from './smtd-bfa-dance.json';
import s4 from './smtd-bfa-directing.json';
import s5 from './smtd-bfa-interarts.json';
import s6 from './smtd-bfa-jazz-contemplative-studies.json';
import s7 from './smtd-bfa-musical-theatre.json';
import s8 from './smtd-bfa-performing-arts-technology.json';
import s9 from './smtd-bfa-theatre-design-production.json';
import s10 from './smtd-bm-choral-music-education.json';
import s11 from './smtd-bm-composition.json';
import s12 from './smtd-bm-harp-performance.json';
import s13 from './smtd-bm-instrumental-music-education.json';
import s14 from './smtd-bm-jazz-contemporary-improvisation.json';
import s15 from './smtd-bm-multiple-wind-instruments.json';
import s16 from './smtd-bm-music-and-technology.json';
import s17 from './smtd-bm-music-theory.json';
import s18 from './smtd-bm-musicology.json';
import s19 from './smtd-bm-organ-performance-sacred-music.json';
import s20 from './smtd-bm-piano-performance.json';
import s21 from './smtd-bm-strings-performance.json';
import s22 from './smtd-bm-voice-performance.json';
import s23 from './smtd-bm-winds-percussion-performance.json';
import s24 from './smtd-bma-multidisciplinary.json';
import s25 from './smtd-bma-performance.json';
import s26 from './smtd-bs-sound-engineering.json';
import s27 from './smtd-bta.json';
import n1 from './nursing-bsn.json';
import k1 from './kines-applied-exercise-science.json';
import k2 from './kines-movement-science.json';
import k3 from './kines-sport-management.json';

export const all: Major[] = [
  p1 as Major,
  p2 as Major,
  p3 as Major,
  p4 as Major,
  p5 as Major,
  p6 as Major,
  p7 as Major,
  p8 as Major,
  p9 as Major,
  p10 as Major,
  p11 as Major,
  p12 as Major,
  p13 as Major,
  p14 as Major,
  p15 as Major,
  p16 as Major,
  p17 as Major,
  p18 as Major,
  p19 as Major,
  p20 as Major,
  p21 as Major,
  p23 as Major,
  p24 as Major,
  p25 as Major,
  p26 as Major,
  p27 as Major,
  p28 as Major,
  p29 as Major,
  p30 as Major,
  p31 as Major,
  p32 as Major,
  p33 as Major,
  p34 as Major,
  p35 as Major,
  p36 as Major,
  p37 as Major,
  p38 as Major,
  p39 as Major,
  p40 as Major,
  p41 as Major,
  p42 as Major,
  p43 as Major,
  p44 as Major,
  p45 as Major,
  p46 as Major,
  p47 as Major,
  p48 as Major,
  p49 as Major,
  p50 as Major,
  p51 as Major,
  p52 as Major,
  p53 as Major,
  p54 as Major,
  p55 as Major,
  p56 as Major,
  p57 as Major,
  p58 as Major,
  p59 as Major,
  p60 as Major,
  p61 as Major,
  p62 as Major,
  p63 as Major,
  p64 as Major,
  p65 as Major,
  p66 as Major,
  p67 as Major,
  p68 as Major,
  p69 as Major,
  p70 as Major,
  p71 as Major,
  p72 as Major,
  p73 as Major,
  c1 as Major,
  c2 as Major,
  c3 as Major,
  c4 as Major,
  c5 as Major,
  c6 as Major,
  c7 as Major,
  c8 as Major,
  c9 as Major,
  c10 as Major,
  c11 as Major,
  c12 as Major,
  c13 as Major,
  c14 as Major,
  c15 as Major,
  c16 as Major,
  c17 as Major,
  c18 as Major,
  r1 as Major,
  u1 as Major,
  u2 as Major,
  s1 as Major,
  s2 as Major,
  s3 as Major,
  s4 as Major,
  s5 as Major,
  s6 as Major,
  s7 as Major,
  s8 as Major,
  s9 as Major,
  s10 as Major,
  s11 as Major,
  s12 as Major,
  s13 as Major,
  s14 as Major,
  s15 as Major,
  s16 as Major,
  s17 as Major,
  s18 as Major,
  s19 as Major,
  s20 as Major,
  s21 as Major,
  s22 as Major,
  s23 as Major,
  s24 as Major,
  s25 as Major,
  s26 as Major,
  s27 as Major,
  n1 as Major,
  k1 as Major,
  k2 as Major,
  k3 as Major,
];
