// AUTO-GENERATED by scripts/ingest/lsa-generate-stubs.ts. Do not edit by hand.
import type { Major } from '@/lib/types';
import p1 from './lsa-afroamerican-and-african-studies.json';
import p2 from './lsa-american-culture.json';
import p3 from './lsa-anthropology.json';
import p4 from './lsa-archaeology-of-the-ancient-mediterranean.json';
import p5 from './lsa-arts-and-ideas-in-the-humanities.json';
import p6 from './lsa-asian-studies.json';
import p7 from './lsa-astronomy-and-astrophysics.json';
import p8 from './lsa-biochemistry-bs.json';
import p9 from './lsa-biology.json';
import p10 from './lsa-biomolecular-science-ab-or-bs.json';
import p11 from './lsa-biophyschology-cognition-and-neuroscience-bcn.json';
import p12 from './lsa-biophysics-bs.json';
import p13 from './lsa-biotechnology-and-bioenvironmental-sciences.json';
import p14 from './lsa-cell-and-molecular-biology-and-biomedical-engineering.json';
import p15 from './lsa-cell-and-molecular-biology.json';
import p16 from './lsa-chemistry.json';
import p17 from './lsa-classical-civilization.json';
import p18 from './lsa-classical-languages-and-literatures.json';
import p19 from './lsa-cognitive-science.json';
import p20 from './lsa-communication-studies.json';
import p21 from './lsa-comparative-literature-arts-and-media.json';
import p23 from './lsa-creative-writing-and-literature.json';
import p24 from './lsa-data-science.json';
import p25 from './lsa-drama.json';
import p26 from './lsa-earth-and-environmental-sciences.json';
import p27 from './lsa-ecology-and-evolutionary-biology-eeb.json';
import p28 from './lsa-economics.json';
import p29 from './lsa-english.json';
import p30 from './lsa-environment.json';
import p31 from './lsa-french-and-francophone-studies.json';
import p32 from './lsa-gender-and-health.json';
import p33 from './lsa-general-biology.json';
import p34 from './lsa-general-studies.json';
import p35 from './lsa-german.json';
import p36 from './lsa-greek-ancient-language-and-literature.json';
import p37 from './lsa-greek-modern-language-and-culture.json';
import p38 from './lsa-history-of-art.json';
import p39 from './lsa-history.json';
import p40 from './lsa-human-origins-biology-and-behavior.json';
import p41 from './lsa-interdisciplinary-astronomy-ba-or-bs.json';
import p42 from './lsa-interdisciplinary-chemical-sciences-ics-ab-or-bs.json';
import p43 from './lsa-interdiscplinary-physics-ab-or-bs.json';
import p44 from './lsa-international-studies.json';
import p45 from './lsa-italian.json';
import p46 from './lsa-judaic-studies.json';
import p47 from './lsa-latin-american-and-caribbean-studies.json';
import p48 from './lsa-latin-language-and-literature.json';
import p49 from './lsa-latina-latino-studies.json';
import p50 from './lsa-linguistics.json';
import p51 from './lsa-mathematics.json';
import p52 from './lsa-microbiology.json';
import p53 from './lsa-middle-eastern-and-north-african-studies.json';
import p54 from './lsa-near-eastern-studies.json';
import p55 from './lsa-neuroscience.json';
import p56 from './lsa-organizational-studies.json';
import p57 from './lsa-philosophy-political-science-economics.json';
import p58 from './lsa-philosophy.json';
import p59 from './lsa-physics.json';
import p60 from './lsa-polish.json';
import p61 from './lsa-political-science.json';
import p62 from './lsa-psychology-general-social-science.json';
import p63 from './lsa-romance-languages-and-literatures.json';
import p64 from './lsa-russian-east-european-and-eurasian-studies.json';
import p65 from './lsa-russian.json';
import p66 from './lsa-screen-arts-and-cultures.json';
import p67 from './lsa-social-theory-and-practice.json';
import p68 from './lsa-sociology.json';
import p69 from './lsa-spanish.json';
import p70 from './lsa-statistics.json';
import p71 from './lsa-translation.json';
import p72 from './lsa-womens-studies.json';
import p73 from './lsa-computer-science-2.json';

export const all: Major[] = [
  p1 as Major,
  p2 as Major,
  p3 as Major,
  p4 as Major,
  p5 as Major,
  p6 as Major,
  p7 as Major,
  p8 as Major,
  p9 as Major,
  p10 as Major,
  p11 as Major,
  p12 as Major,
  p13 as Major,
  p14 as Major,
  p15 as Major,
  p16 as Major,
  p17 as Major,
  p18 as Major,
  p19 as Major,
  p20 as Major,
  p21 as Major,
  p23 as Major,
  p24 as Major,
  p25 as Major,
  p26 as Major,
  p27 as Major,
  p28 as Major,
  p29 as Major,
  p30 as Major,
  p31 as Major,
  p32 as Major,
  p33 as Major,
  p34 as Major,
  p35 as Major,
  p36 as Major,
  p37 as Major,
  p38 as Major,
  p39 as Major,
  p40 as Major,
  p41 as Major,
  p42 as Major,
  p43 as Major,
  p44 as Major,
  p45 as Major,
  p46 as Major,
  p47 as Major,
  p48 as Major,
  p49 as Major,
  p50 as Major,
  p51 as Major,
  p52 as Major,
  p53 as Major,
  p54 as Major,
  p55 as Major,
  p56 as Major,
  p57 as Major,
  p58 as Major,
  p59 as Major,
  p60 as Major,
  p61 as Major,
  p62 as Major,
  p63 as Major,
  p64 as Major,
  p65 as Major,
  p66 as Major,
  p67 as Major,
  p68 as Major,
  p69 as Major,
  p70 as Major,
  p71 as Major,
  p72 as Major,
  p73 as Major,
];
