// AUTO-GENERATED by scripts/ingest/lsa-generate-stubs.ts. Do not edit by hand.
import type { Minor } from '@/lib/types';
import p0 from './lsa-afroamerican-and-african-studies-minor.json';
import p1 from './lsa-american-culture-minor.json';
import p2 from './lsa-anthropology-minor.json';
import p3 from './lsa-arab-and-muslim-american-studies-minor.json';
import p4 from './lsa-arabic-studies-minor.json';
import p5 from './lsa-archaeology-of-the-ancient-mediterranean-minor.json';
import p6 from './lsa-architecture-minor.json';
import p7 from './lsa-art-and-design-minor.json';
import p8 from './lsa-asian-languages-and-cultures-minor.json';
import p9 from './lsa-asian-pacific-islander-american-studies-minor.json';
import p10 from './lsa-asian-studies-minor.json';
import p11 from './lsa-astronomy-and-astrophysics-minor.json';
import p12 from './lsa-biochemistry-minor.json';
import p13 from './lsa-biological-anthropology-minor.json';
import p14 from './lsa-biology-minor.json';
import p15 from './lsa-biophysics-minor.json';
import p16 from './lsa-bosnian-croatian-serbian-literature-and-culture-minor.json';
import p17 from './lsa-business-minor.json';
import p18 from './lsa-chemistry-minor.json';
import p19 from './lsa-civil-engineering-minor.json';
import p20 from './lsa-classical-civilization-minor.json';
import p21 from './lsa-classical-languages-minor.json';
import p22 from './lsa-climate-and-space-sciences-and-engineering-minor.json';
import p23 from './lsa-community-action-and-social-change-minor.json';
import p24 from './lsa-complex-systems-minor.json';
import p25 from './lsa-computer-science-minor.json';
import p26 from './lsa-computing-for-expression-minor.json';
import p27 from './lsa-computing-for-scientific-discovery-minor.json';
import p28 from './lsa-creative-writing-minor.json';
import p29 from './lsa-crime-and-justice-minor.json';
import p30 from './lsa-cultures-and-literatures-of-eastern-europe-minor.json';
import p31 from './lsa-czech-language-literature-and-culture-minor.json';
import p32 from './lsa-dance-minor.json';
import p33 from './lsa-data-science-minor.json';
import p34 from './lsa-design-and-production-minor.json';
import p35 from './lsa-digital-studies-minor.json';
import p36 from './lsa-disability-studies-minor.json';
import p37 from './lsa-drama-minor.json';
import p38 from './lsa-dutch-language-and-culture-minor.json';
import p39 from './lsa-earth-sciences-minor.json';
import p40 from './lsa-east-european-studies-minor.json';
import p41 from './lsa-ecology-and-evolutionary-biology-minor.json';
import p42 from './lsa-economics-minor.json';
import p43 from './lsa-education-for-empowerment-minor.json';
import p44 from './lsa-electrical-engineering-minor.json';
import p45 from './lsa-energy-and-science-policy-minor.json';
import p46 from './lsa-english-minor.json';
import p47 from './lsa-entrepreneurship-minor.json';
import p48 from './lsa-environment-minor.json';
import p49 from './lsa-environmental-justice-minor.json';
import p50 from './lsa-epistemology-and-philosophy-of-science-minor.json';
import p51 from './lsa-food-and-the-environment-minor.json';
import p52 from './lsa-french-and-francophone-studies-minor.json';
import p53 from './lsa-gender-and-health-minor.json';
import p54 from './lsa-gender-race-and-nation-minor.json';
import p55 from './lsa-general-philosophy-minor.json';
import p56 from './lsa-geology-minor.json';
import p57 from './lsa-geospatial-science-minor.json';
import p58 from './lsa-german-studies-minor.json';
import p59 from './lsa-global-history-minor.json';
import p60 from './lsa-global-media-studies-minor.json';
import p61 from './lsa-global-theatre-and-ethnic-studies-minor.json';
import p62 from './lsa-greek-modern-language-and-culture-minor.json';
import p63 from './lsa-history-minor.json';
import p64 from './lsa-history-of-art-minor.json';
import p65 from './lsa-history-of-law-and-policy-minor.json';
import p66 from './lsa-history-of-medicine-and-health-minor.json';
import p67 from './lsa-human-anatomy-and-physiology-minor.json';
import p68 from './lsa-interdisciplinary-astronomy-minor.json';
import p69 from './lsa-intergroup-relations-education-minor.json';
import p70 from './lsa-international-studies-minor.json';
import p71 from './lsa-islamic-studies-minor.json';
import p72 from './lsa-italian-minor.json';
import p73 from './lsa-judaic-studies-minor.json';
import p74 from './lsa-latin-american-and-caribbean-studies-minor.json';
import p75 from './lsa-latina-o-studies-minor.json';
import p76 from './lsa-law-justice-and-social-change-minor.json';
import p77 from './lsa-lesbian-gay-bisexual-transgender-queer-sexuality-studies-minor.json';
import p78 from './lsa-linguistics-minor.json';
import p79 from './lsa-mathematics-minor.json';
import p80 from './lsa-medical-anthropology-minor.json';
import p81 from './lsa-medieval-and-early-modern-studies-minor.json';
import p82 from './lsa-modern-middle-eastern-and-north-african-studies-minor.json';
import p83 from './lsa-moral-and-political-philosophy-minor.json';
import p84 from './lsa-multidisciplinary-design-minor.json';
import p85 from './lsa-museum-studies-minor.json';
import p86 from './lsa-music-minor.json';
import p87 from './lsa-native-american-studies-minor.json';
import p88 from './lsa-near-eastern-languages-and-cultures-minor.json';
import p89 from './lsa-oceanography-minor.json';
import p90 from './lsa-paleontology-minor.json';
import p91 from './lsa-performing-arts-management-minor.json';
import p92 from './lsa-pharmacology-minor.json';
import p93 from './lsa-physics-minor.json';
import p94 from './lsa-playwriting-minor.json';
import p95 from './lsa-polish-language-literature-and-culture-minor.json';
import p96 from './lsa-political-science-minor.json';
import p97 from './lsa-portuguese-minor.json';
import p98 from './lsa-public-policy-minor.json';
import p99 from './lsa-quantitative-methods-social-sciences-minor.json';
import p100 from './lsa-religion-minor.json';
import p101 from './lsa-russian-language-literature-and-culture-minor.json';
import p102 from './lsa-russian-studies-minor.json';
import p103 from './lsa-scandinavian-studies-minor.json';
import p104 from './lsa-science-technology-and-society-sts-minor.json';
import p105 from './lsa-social-class-and-inequality-studies-minor.json';
import p106 from './lsa-social-media-analysis-and-design-minor.json';
import p107 from './lsa-spanish-language-literature-and-culture-minor.json';
import p108 from './lsa-statistics-minor.json';
import p109 from './lsa-sustainability-minor.json';
import p110 from './lsa-translation-studies-minor.json';
import p111 from './lsa-ukrainian-language-literature-and-culture-minor.json';
import p112 from './lsa-urban-studies-minor.json';
import p113 from './lsa-user-experience-design-minor.json';
import p114 from './lsa-water-and-the-environment-minor.json';
import p115 from './lsa-wrtiting-minor.json';
import p116 from './lsa-yiddish-studies-minor.json';

export const all: Minor[] = [
  p0 as Minor,
  p1 as Minor,
  p2 as Minor,
  p3 as Minor,
  p4 as Minor,
  p5 as Minor,
  p6 as Minor,
  p7 as Minor,
  p8 as Minor,
  p9 as Minor,
  p10 as Minor,
  p11 as Minor,
  p12 as Minor,
  p13 as Minor,
  p14 as Minor,
  p15 as Minor,
  p16 as Minor,
  p17 as Minor,
  p18 as Minor,
  p19 as Minor,
  p20 as Minor,
  p21 as Minor,
  p22 as Minor,
  p23 as Minor,
  p24 as Minor,
  p25 as Minor,
  p26 as Minor,
  p27 as Minor,
  p28 as Minor,
  p29 as Minor,
  p30 as Minor,
  p31 as Minor,
  p32 as Minor,
  p33 as Minor,
  p34 as Minor,
  p35 as Minor,
  p36 as Minor,
  p37 as Minor,
  p38 as Minor,
  p39 as Minor,
  p40 as Minor,
  p41 as Minor,
  p42 as Minor,
  p43 as Minor,
  p44 as Minor,
  p45 as Minor,
  p46 as Minor,
  p47 as Minor,
  p48 as Minor,
  p49 as Minor,
  p50 as Minor,
  p51 as Minor,
  p52 as Minor,
  p53 as Minor,
  p54 as Minor,
  p55 as Minor,
  p56 as Minor,
  p57 as Minor,
  p58 as Minor,
  p59 as Minor,
  p60 as Minor,
  p61 as Minor,
  p62 as Minor,
  p63 as Minor,
  p64 as Minor,
  p65 as Minor,
  p66 as Minor,
  p67 as Minor,
  p68 as Minor,
  p69 as Minor,
  p70 as Minor,
  p71 as Minor,
  p72 as Minor,
  p73 as Minor,
  p74 as Minor,
  p75 as Minor,
  p76 as Minor,
  p77 as Minor,
  p78 as Minor,
  p79 as Minor,
  p80 as Minor,
  p81 as Minor,
  p82 as Minor,
  p83 as Minor,
  p84 as Minor,
  p85 as Minor,
  p86 as Minor,
  p87 as Minor,
  p88 as Minor,
  p89 as Minor,
  p90 as Minor,
  p91 as Minor,
  p92 as Minor,
  p93 as Minor,
  p94 as Minor,
  p95 as Minor,
  p96 as Minor,
  p97 as Minor,
  p98 as Minor,
  p99 as Minor,
  p100 as Minor,
  p101 as Minor,
  p102 as Minor,
  p103 as Minor,
  p104 as Minor,
  p105 as Minor,
  p106 as Minor,
  p107 as Minor,
  p108 as Minor,
  p109 as Minor,
  p110 as Minor,
  p111 as Minor,
  p112 as Minor,
  p113 as Minor,
  p114 as Minor,
  p115 as Minor,
  p116 as Minor,
];
